name: 'Run MetaTrader Compiler'
description: 'Run MetaTrader Compiler'
author: 'Martijn Riemers'

inputs:
  files:
    description: 'Files to compile'
    required: true
  include:
    description: 'Additional directory to include for compilation'
    required: false

outputs:
  results:
    description: 'Compilation results including output binary'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'bar-chart'
  color: 'green'
