name: Perform a Release

on:
  workflow_dispatch:
    inputs:
      release-it-arg:
        description: Argument to release-it
        default: minor
        required: true

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install
      - run: npm test
      - run: npm run release -- "${{ github.event.inputs.release-it-arg }}" --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}